"""add_is_deleted_to_expenses

Revision ID: 53a5b775bebb
Revises: e12553742ff4
Create Date: 2026-06-14 16:31:38.697261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a5b775bebb'
down_revision: Union[str, Sequence[str], None] = 'e12553742ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'is_deleted')
    # ### end Alembic commands ###
